### ISSUE TITLE
C99 mode needed to compile cilkscale (not fixed by wmoses recent commit) 

### ISSUE THREAD

**Issue by timkaler** [wmoses/Parallel-IR#36]
/efs/2018-tapir/Tapir-LLVM/projects/compiler-rt/lib/cilkscale/csanrt.c:106:7: error: ‘for’ loop initia
l declarations are only allowed in C99 mode
       for (int i = 0; i < table->num_entries; ++i)

Note: after talking with TB I realize that an attempt was made to fix this bug. But it does not appear to have worked. I'm compiling with gcc 4.8.5

**Comment by wsmoses** [comment]
Closed: This is equivalent to issue is Compiler RT issue 1 (https://github.com/wsmoses/Tapir-compiler-rt/issues/1)
