### ISSUE TITLE
Compilation bug preventing divide and conquer loop parallelization

### ISSUE THREAD

**Issue by timkaler** [wmoses/Parallel-IR#38]
To reproduce: https://github.mit.edu/Supertech-Connectomics/sift_features/tree/1-24-2018-tapir-bug (branch 1-24-2018-tapir-bug) and checkout commit 95540f89caf784d42f6b8ca4614efd10328edbf3 on that branch.

A workaround that appears to avoid the compilation problem is to change the return value of Section::parameter_optimization to be void (and return result via argument reference).

**Comment by neboat** [comment]
I've tested the committed fix on the source code specified in this issue, and I now observe no errors in compilation.
