### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by stelleg** [wmoses/Parallel-IR#67]
So I'm not sure why the CI is passing, but I'm getting test failures that I wasn't a few months ago. I haven't had a chance to narrow down exactly when the issue was introduced, but I get no unexpected failures on commit `7352407d063c8bac796926ca618e14d8eca87735` from January, for example. On the current HEAD, `1482504e234a65bffc8c54de8de9fc877822345d`, I'm getting 1767 unexpected failures when running `make check`. 

When I get the chance I'll try and look into what could have caused all the failures between now and then, but in the meantime I thought it was worth opening an issue. I'm curious if others can reproduce these failures.

**Comment by neboat** [comment]
That's odd.  Are you seeing these failures occur on a Release build?  I've seen some tests that pass on the Release build apparently fail on a Debug build, due to the system running out of memory or disc space.  I think I've seen this same phenomenon occur with vanilla LLVM, though I'm not sure of that right now.

**Comment by stelleg** [comment]
I did try with the exact cmake line from the CI configuration (which is a Release build), and IIRC there were less errors, but still  around 400. I believe the discrepancy there is due to the CI script only building for the host architecture, while many of the errors I'm seeing are for other targets. I'd encourage you to leave the other architectures in enabled in CI, as it would be great to have Tapir continue to work on platforms like ARM and Power.

I'm pretty confident it's not running out of memory or disk space, as I'm running on a box with 500G of ram and plenty of disk space.

**Comment by stelleg** [comment]
So I just had a look and it looks like almost all of them are failing in `pushUpReattaches`, which was just added in the last commit. An example stack trace:
```
#0 0x000000000236a9f4 PrintStackTraceSignalHandler(void*) (/dev/shm/build/./bin/opt+0x236a9f4)
#1 0x000000000236acd6 SignalHandler(int) (/dev/shm/build/./bin/opt+0x236acd6)
#2 0x0000149cd15a95e0 __restore_rt (/usr/lib64/libpthread.so.0+0xf5e0)
#3 0x0000000001efb7a4 llvm::Use::getUser() const (/dev/shm/build/./bin/opt+0x1efb7a4)
#4 0x0000000002411dab pushUpReattaches(llvm::BasicBlock*) (/dev/shm/build/./bin/opt+0x2411dab)
#5 0x0000000002411092 (/dev/shm/build/./bin/opt+0x2411092)
#6 0x0000000002410fb8 llvm::SimplifyCFG(llvm::BasicBlock*, llvm::TargetTransformInfo const&, unsigned int, llvm::AssumptionCache*, llvm::SmallPtrSetImpl<llvm::BasicBlock*>*, bool) (/dev/shm/build/./bin/opt+0x2410fb8)
#7 0x00000000022c2de9 iterativelySimplifyCFG(llvm::Function&, llvm::TargetTransformInfo const&, llvm::AssumptionCache*, unsigned int, bool) (/dev/shm/build/./bin/opt+0x22c2de9)
#8 0x00000000022c260e simplifyFunctionCFG(llvm::Function&, llvm::TargetTransformInfo const&, llvm::AssumptionCache*, int, bool) (/dev/shm/build/./bin/opt+0x22c260e)
#9 0x0000000001ec7d4b llvm::FPPassManager::runOnFunction(llvm::Function&) (/dev/shm/build/./bin/opt+0x1ec7d4b)
#10 0x0000000001ec7fb3 llvm::FPPassManager::runOnModule(llvm::Module&) (/dev/shm/build/./bin/opt+0x1ec7fb3)
#11 0x0000000001ec83f8 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/dev/shm/build/./bin/opt+0x1ec83f8)
#12 0x0000000000ff357e main (/dev/shm/build/./bin/opt+0xff357e)
#13 0x0000149cd0111c05 __libc_start_main (/usr/lib64/libc.so.6+0x21c05)
#14 0x0000000000fe6029 _start (/dev/shm/build/./bin/opt+0xfe6029)
```

Edit: I've just confirmed that reverting `1482504e234a65bffc8c54de8de9fc877822345d` fixes the issue.

**Comment by wsmoses** [comment]
Just to make trying to debug a bit easier, what is the test case above?

**Comment by stelleg** [comment]
Sorry, not actually sure. I just chose one of the many that were failing randomly and pasted it here. If the tests aren't failing for you (which they don't seem to be according to your CI logs) I'm happy to dig in and figure out whats going on. I probably can't get around to it until next week though, and thought I should just open the issue in the meantime.

**Comment by stelleg** [comment]
So it looks like this was an issue with using a bleeding edge Clang to compile Tapir. Compiling with older versions of Clang and GCC remove the issue. Sorry for false alarm.

**Comment by stelleg** [comment]
So it looks like the failures occur when Tapir is built with Clang/LLVM 6, but not when it is built with Clang/LLVM 5. Trying to debug now.

**Comment by stelleg** [comment]
Looks like Clang 6 gets aggressive with how it treats missing return values. PR #68 fixes the test issues.
