### ISSUE TITLE
cilk_for sometimes doesn't work with clang

### ISSUE THREAD

**Issue by kezilu** [wmoses/Parallel-IR#7]
Compilation fails; tried debug and cilksan.

I received the following long output:

clang -std=gnu99 -Wall -ftapir -g -O0 -gdwarf-3  -o collision_world.o -c collision_world.c
clang: /home/ubuntu/Parallel-IR/include/llvm/Transforms/CilkABI.h:1131: bool llvm::cilk::populateDetachedCFG(const llvm::DetachInst&, llvm::DominatorTree&, llvm::SmallPtrSet<llvm::BasicBlock*, 32u>&, llvm::SmallVector<llvm::BasicBlock*, 32u>&, bool, bool): Assertion `term != &detach && "Found recursive detach!"' failed.
#0 0x00000000031e90e7 llvm::sys::PrintStackTrace(llvm::raw_ostream&) /home/ubuntu/Parallel-IR/lib/Support/Unix/Signals.inc:402:0
#1 0x00000000031e94a9 PrintStackTraceSignalHandler(void*) /home/ubuntu/Parallel-IR/lib/Support/Unix/Signals.inc:470:0
#2 0x00000000031e7814 llvm::sys::RunSignalHandlers() /home/ubuntu/Parallel-IR/lib/Support/Signals.cpp:44:0
#3 0x00000000031e8a78 SignalHandler(int) /home/ubuntu/Parallel-IR/lib/Support/Unix/Signals.inc:256:0
#4 0x00002b57888c2330 __restore_rt (/afs/csail.mit.edu/proj/courses/6.172/tapir/otherlibs/lib/x86_64-linux-gnu/libpthread.so.0+0x10330)
#5 0x00002b5789741c37 gsignal (/afs/csail.mit.edu/proj/courses/6.172/tapir/otherlibs/lib/x86_64-linux-gnu/libc.so.6+0x36c37)
#6 0x00002b5789745028 abort (/afs/csail.mit.edu/proj/courses/6.172/tapir/otherlibs/lib/x86_64-linux-gnu/libc.so.6+0x3a028)
#7 0x00002b578973abf6 (/afs/csail.mit.edu/proj/courses/6.172/tapir/otherlibs/lib/x86_64-linux-gnu/libc.so.6+0x2fbf6)
#8 0x00002b578973aca2 (/afs/csail.mit.edu/proj/courses/6.172/tapir/otherlibs/lib/x86_64-linux-gnu/libc.so.6+0x2fca2)
#9 0x0000000003257ea5 llvm::cilk::populateDetachedCFG(llvm::DetachInst const&, llvm::DominatorTree&, llvm::SmallPtrSet<llvm::BasicBlock*, 32u>&, llvm::SmallVector<llvm::BasicBlock*, 32u>&, bool, bool) /home/ubuntu/Parallel-IR/include/llvm/Transforms/CilkABI.h:1132:0
#10 0x000000000325f095 (anonymous namespace)::Loop2Cilk::performDAC(llvm::Loop*, llvm::LPPassManager&) /home/ubuntu/Parallel-IR/lib/Transforms/Utils/Loop2Cilk.cpp:944:0
#11 0x00000000032604f7 (anonymous namespace)::Loop2Cilk::runOnLoop(llvm::Loop*, llvm::LPPassManager&) /home/ubuntu/Parallel-IR/lib/Transforms/Utils/Loop2Cilk.cpp:1153:0
#12 0x000000000401d5e0 llvm::LPPassManager::runOnFunction(llvm::Function&) /home/ubuntu/Parallel-IR/lib/Analysis/LoopPass.cpp:198:0
#13 0x0000000002ccff10 llvm::FPPassManager::runOnFunction(llvm::Function&) /home/ubuntu/Parallel-IR/lib/IR/LegacyPassManager.cpp:1522:0
#14 0x0000000002cd00a3 llvm::FPPassManager::runOnModule(llvm::Module&) /home/ubuntu/Parallel-IR/lib/IR/LegacyPassManager.cpp:1543:0
#15 0x0000000002cd042f (anonymous namespace)::MPPassManager::runOnModule(llvm::Module&) /home/ubuntu/Parallel-IR/lib/IR/LegacyPassManager.cpp:1599:0
#16 0x0000000002cd0b20 llvm::legacy::PassManagerImpl::run(llvm::Module&) /home/ubuntu/Parallel-IR/lib/IR/LegacyPassManager.cpp:1702:0
#17 0x0000000002cd0d61 llvm::legacy::PassManager::run(llvm::Module&) /home/ubuntu/Parallel-IR/lib/IR/LegacyPassManager.cpp:1734:0
#18 0x0000000003461d31 (anonymous namespace)::EmitAssemblyHelper::EmitAssembly(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) /home/ubuntu/Parallel-IR/tools/clang/lib/CodeGen/BackendUtil.cpp:730:0
#19 0x00000000034627ad clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) /home/ubuntu/Parallel-IR/tools/clang/lib/CodeGen/BackendUtil.cpp:820:0
#20 0x0000000003def400 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) /home/ubuntu/Parallel-IR/tools/clang/lib/CodeGen/CodeGenAction.cpp:195:0
#21 0x000000000484653a clang::ParseAST(clang::Sema&, bool, bool) /home/ubuntu/Parallel-IR/tools/clang/lib/Parse/ParseAST.cpp:169:0
#22 0x00000000039a77aa clang::ASTFrontendAction::ExecuteAction() /home/ubuntu/Parallel-IR/tools/clang/lib/Frontend/FrontendAction.cpp:559:0
#23 0x0000000003dee46a clang::CodeGenAction::ExecuteAction() /home/ubuntu/Parallel-IR/tools/clang/lib/CodeGen/CodeGenAction.cpp:868:0
#24 0x00000000039a7251 clang::FrontendAction::Execute() /home/ubuntu/Parallel-IR/tools/clang/lib/Frontend/FrontendAction.cpp:462:0
#25 0x0000000003958476 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /home/ubuntu/Parallel-IR/tools/clang/lib/Frontend/CompilerInstance.cpp:872:0
#26 0x0000000003ac10b8 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /home/ubuntu/Parallel-IR/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:246:0
#27 0x000000000189bb22 cc1_main(llvm::ArrayRef<char const*>, char const_, void_) /home/ubuntu/Parallel-IR/tools/clang/tools/driver/cc1_main.cpp:181:0
#28 0x0000000001892125 ExecuteCC1Tool(llvm::ArrayRef<char const*>, llvm::StringRef) /home/ubuntu/Parallel-IR/tools/clang/tools/driver/driver.cpp:299:0
#29 0x0000000001892bac main /home/ubuntu/Parallel-IR/tools/clang/tools/driver/driver.cpp:380:0
#30 0x00002b578972cf45 __libc_start_main (/afs/csail.mit.edu/proj/courses/6.172/tapir/otherlibs/lib/x86_64-linux-gnu/libc.so.6+0x21f45)
#31 0x000000000188fa79 _start (/afs/csail.mit.edu/proj/courses/6.172/tapir-3.0/bin/clang+0x188fa79)

Stack dump:
0.  Program arguments: /afs/csail.mit.edu/proj/courses/6.172/tapir-3.0/bin/clang -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -main-file-name collision_world.c -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debug-info-kind=limited -dwarf-version=3 -debugger-tuning=gdb -coverage-file /afs/athena.mit.edu/user/k/e/kezilu/projects/project2/collision_world.o -resource-dir /afs/csail.mit.edu/proj/courses/6.172/tapir-3.0/bin/../lib/clang/4.0.0 -I/usr/include/x86_64-linux-gnu/ -I/usr/include/x86_64-linux-gnu/ -internal-isystem /usr/local/include -internal-isystem /afs/csail.mit.edu/proj/courses/6.172/tapir-3.0/bin/../lib/clang/4.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O0 -Wall -std=gnu99 -fdebug-compilation-dir /afs/athena.mit.edu/user/k/e/kezilu/projects/project2 -ferror-limit 19 -fmessage-length 145 -ftapir -fobjc-runtime=gcc -fdiagnostics-show-option -o collision_world.o -x c collision_world.c 
1.  <eof> parser at end of file
2.  Per-module optimization passes
3.  Running pass 'Function Pass Manager' on module 'collision_world.c'.
4.  Running pass 'Loop Pass Manager' on function '@find_self_intersections'
5.  Running pass 'Find cilk for loops and use more efficient runtime' on basic block '%pfor.cond1'
clang: error: unable to execute command: Aborted
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 4.0.0 (https://github.com/wsmoses/Cilk-Clang.git 1c283243292d1417e1eecf5933c24e30b77c7609) (https://github.com/wsmoses/Parallel-IR.git a2c6e22dd11c4212dbb64ce15020f677d77ed479)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /afs/csail.mit.edu/proj/courses/6.172/tapir-3.0/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 

---

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/collision_world-fbc1b1.c
clang: note: diagnostic msg: /tmp/collision_world-fbc1b1.sh
clang: note: diagnostic msg: 

---

make: **\* [collision_world.o] Error 254

**Comment by sachindshinde** [comment]
Attached is a copy of the code that produces the issue.

[screensaver.tar.gz](https://github.com/wsmoses/Parallel-IR/files/543458/screensaver.tar.gz)

**Comment by wsmoses** [comment]
Fixed in commit fe05c97
