### ISSUE TITLE
Name all outlined functions so they can be programmatically mapped back to original, demanglable function names

### ISSUE THREAD

**Issue by VictorYing** [wmoses/Parallel-IR#78]
I want to make it easy for scripts and tools (e.g., profiling scripts) with only access to the binary as it runs to look at the name of an outlined task function and map that back to the name of the original function the code came from, and specifically I want tools to be able to easily identify what portion of an outlined task function's name was the original mangled name of a C++ function, to automatically demangle that original mangled function name (e.g., with `c++filt` or `abi::__cxa_demangle`) to report a correctly demanged C++ function name to a human user.

I therefore propose that the names of outlined task functions should begin with the name of the frontend-generated function from whence the code was outlined, followed by a delimiter that would never be generated by the frontend, such as a period, followed by whatever additional suffixes.

The `CreateHelper` utility currently *almost* does this, generating names for outlined functions by concatenating the name of the function the code came from with an underscore followed by a BasicBlock's name and a caller-specified suffix:
https://github.com/wsmoses/Tapir-LLVM/blob/2031611b65d67c1986af06c5f98b3c1d5e140d51/lib/Transforms/Tapir/Outline.cpp#L238-L241
This works well enough to make collisions rare to nonexistant, since basic block names are unique within a function, although there was always the risk that the function name, basic block name, and suffix might combine to collide with some other existing function's name. This generates function names like `foo_for.body.preheader.cilk`, for example, if a Cilk task starting with a block named "for.body.preheader" from the function `foo` was outlined. Unfortunately, given that function names themselves may have multiple underscores and basic block names may include anything a LLVM transform pass writer thought to use as a name of a block created during some transformation, it's hard for a tool to know how to find the right underscore that divides the original function name from the rest.

Since at this point it seems that we're already happy generating function names with periods in them, my proposal would be to replace the underscore joining the function name and basic block name with a string that starts with a period like ".outline_", resulting in function names like `foo.outline_for.body.preheader.cilk`. Given this name, a tool can easily search for the first occurance of a period or the string ".outline" and remove everything after that to determine the original function name was `foo`.

**Comment by VictorYing** [comment]
I've addressed this my way in the Swarm compiler here: https://github.mit.edu/swarm/Swarm-IR/pull/550 feel free to cherry-pick this fix over to Tapir

**Comment by neboat** [comment]
I like this suggestion, and I'm trying out an implementation in my local copy.

**Comment by VictorYing** [comment]
Closed by 035ed673696877efebf7a5f9e4a780db30412e58 a.k.a. 65b11aad13a1340bc8988d7c8df743d345373ac5
