### ISSUE TITLE
cilksan bug

### ISSUE THREAD

**Issue by wheatman** [wmoses/Parallel-IR#84]
The code can be found here https://github.com/wheatman/extended-csr/tree/cilksan-issue

#0 0x000000000152cbda llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/efs/tools/tapir-6/build/bin/clang-6.0+0x152cbda)
#1 0x000000000152ae2e llvm::sys::RunSignalHandlers() (/efs/tools/tapir-6/build/bin/clang-6.0+0x152ae2e)
#2 0x000000000152af6a SignalHandler(int) (/efs/tools/tapir-6/build/bin/clang-6.0+0x152af6a)
#3 0x00002ab3efc3c330 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x10330)
#4 0x0000000000cbbffb llvm::FullDependence::isScalar(unsigned int) const (/efs/tools/tapir-6/build/bin/clang-6.0+0xcbbffb)
#5 0x0000000002e2127a DependenceMightRace(std::unique_ptr<llvm::Dependence, std::default_delete<llvm::Dependence> >, llvm::Instruction*, llvm::Instruction*, llvm::Value*, llv
m::Value*, llvm::DenseMap<llvm::Spindle const*, llvm::SmallPtrSet<llvm::Task const*, 2u>, llvm::DenseMapInfo<llvm::Spindle const*>, llvm::detail::DenseMapPair<llvm::Spindle c
onst*, llvm::SmallPtrSet<llvm::Task const*, 2u> > >&, llvm::DenseMap<llvm::Spindle const*, llvm::SmallPtrSet<llvm::Task const*, 2u>, llvm::DenseMapInfo<llvm::Spindle const*>,
 llvm::detail::DenseMapPair<llvm::Spindle const*, llvm::SmallPtrSet<llvm::Task const*, 2u> > >&, llvm::DominatorTree const&, llvm::TaskInfo const&, llvm::LoopInfo&, llvm::Dat
aLayout const&) (/efs/tools/tapir-6/build/bin/clang-6.0+0x2e2127a)
#6 0x0000000002e2547a InstrMightRaceWithTask(llvm::Instruction*, llvm::DenseMap<llvm::Spindle const*, llvm::SmallPtrSet<llvm::Task const*, 2u>, llvm::DenseMapInfo<llvm::Spind
le const*>, llvm::detail::DenseMapPair<llvm::Spindle const*, llvm::SmallPtrSet<llvm::Task const*, 2u> > >&, llvm::DenseMap<llvm::Spindle const*, llvm::SmallPtrSet<llvm::Task
const*, 2u>, llvm::DenseMapInfo<llvm::Spindle const*>, llvm::detail::DenseMapPair<llvm::Spindle const*, llvm::SmallPtrSet<llvm::Task const*, 2u> > >&, llvm::DenseMap<llvm::Ta
sk const*, llvm::SmallVector<llvm::Instruction*, 8u>, llvm::DenseMapInfo<llvm::Task const*>, llvm::detail::DenseMapPair<llvm::Task const*, llvm::SmallVector<llvm::Instruction
*, 8u> > >&, llvm::SmallPtrSetImpl<llvm::Instruction*>&, llvm::DenseMap<llvm::MemTransferInst*, (anonymous namespace)::AccessType, llvm::DenseMapInfo<llvm::MemTransferInst*>,
 llvm::detail::DenseMapPair<llvm::MemTransferInst*, (anonymous namespace)::AccessType> >&, llvm::DominatorTree const&, llvm::TaskInfo const&, llvm::LoopInfo&, llvm::Dependenc
eInfo&, llvm::TargetLibraryInfo const*, llvm::DataLayout const&, bool, bool) [clone .part.825] (/efs/tools/tapir-6/build/bin/clang-6.0+0x2e2547a)
#7 0x0000000002e25aae InstrMightRaceWithTask(llvm::Instruction*, llvm::DenseMap<llvm::Spindle const*, llvm::SmallPtrSet<llvm::Task const*, 2u>, llvm::DenseMapInfo<llvm::Spind
le const*>, llvm::detail::DenseMapPair<llvm::Spindle const*, llvm::SmallPtrSet<llvm::Task const*, 2u> > >&, llvm::DenseMap<llvm::Spindle const*, llvm::SmallPtrSet<llvm::Task
const*, 2u>, llvm::DenseMapInfo<llvm::Spindle const*>, llvm::detail::DenseMapPair<llvm::Spindle const*, llvm::SmallPtrSet<llvm::Task const*, 2u> > >&, llvm::DenseMap<llvm::Ta
sk const*, llvm::SmallVector<llvm::Instruction*, 8u>, llvm::DenseMapInfo<llvm::Task const*>, llvm::detail::DenseMapPair<llvm::Task const*, llvm::SmallVector<llvm::Instruction
*, 8u> > >&, llvm::SmallPtrSetImpl<llvm::Instruction*>&, llvm::DenseMap<llvm::MemTransferInst*, (anonymous namespace)::AccessType, llvm::DenseMapInfo<llvm::MemTransferInst*>,
 llvm::detail::DenseMapPair<llvm::MemTransferInst*, (anonymous namespace)::AccessType> >&, llvm::DominatorTree const&, llvm::TaskInfo const&, llvm::LoopInfo&, llvm::Dependenc
eInfo&, llvm::TargetLibraryInfo const*, llvm::DataLayout const&, bool, bool) (/efs/tools/tapir-6/build/bin/clang-6.0+0x2e25aae)
#8 0x0000000002e2b1c2 (anonymous namespace)::CilkSanitizerImpl::prepareToInstrumentFunction(llvm::Function&) (/efs/tools/tapir-6/build/bin/clang-6.0+0x2e2b1c2)
#9 0x0000000002e2ceab (anonymous namespace)::CilkSanitizerImpl::run() (/efs/tools/tapir-6/build/bin/clang-6.0+0x2e2ceab)
#10 0x0000000002e2e66e (anonymous namespace)::CilkSanitizerLegacyPass::runOnModule(llvm::Module&) [clone .part.831] (/efs/tools/tapir-6/build/bin/clang-6.0+0x2e2e66e)
#11 0x00000000011421c0 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/efs/tools/tapir-6/build/bin/clang-6.0+0x11421c0)
#12 0x00000000016c9926 (anonymous namespace)::EmitAssemblyHelper::EmitAssembly(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pw
rite_stream> >) (/efs/tools/tapir-6/build/bin/clang-6.0+0x16c9926)
#13 0x00000000016cb597 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang
::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (
/efs/tools/tapir-6/build/bin/clang-6.0+0x16cb597)
#14 0x0000000001e587ab clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/efs/tools/tapir-6/build/bin/clang-6.0+0x1e587ab)
#15 0x0000000002025542 clang::ParseAST(clang::Sema&, bool, bool) (/efs/tools/tapir-6/build/bin/clang-6.0+0x2025542)
#16 0x0000000001e58014 clang::CodeGenAction::ExecuteAction() (/efs/tools/tapir-6/build/bin/clang-6.0+0x1e58014)
#17 0x0000000001a5fbfe clang::FrontendAction::Execute() (/efs/tools/tapir-6/build/bin/clang-6.0+0x1a5fbfe)
#18 0x0000000001a37d6d clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/efs/tools/tapir-6/build/bin/clang-6.0+0x1a37d6d)
#19 0x0000000001aeb2c4 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/efs/tools/tapir-6/build/bin/clang-6.0+0x1aeb2c4)
#20 0x0000000000a75c98 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/efs/tools/tapir-6/build/bin/clang-6.0+0xa75c98)
#21 0x0000000000a12401 main (/efs/tools/tapir-6/build/bin/clang-6.0+0xa12401)
#22 0x00002ab3f0b31f45 __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:321:0
#23 0x0000000000a71357 _start (/efs/tools/tapir-6/build/bin/clang-6.0+0xa71357)
Stack dump:
0.      Program arguments: /efs/tools/tapir-6/build/bin/clang-6.0 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -m
ain-file-name test2.cpp -mrelocation-model static -mthread-model posix -menable-no-infs -menable-no-nans -menable-unsafe-fp-math -fno-signed-zeros -mreassociate -freciprocal-
math -fno-trapping-math -ffp-contract=fast -ffast-math -ffinite-math-only -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu haswell -target-fea
ture +sse2 -target-feature +cx16 -target-feature -tbm -target-feature -avx512ifma -target-feature -gfni -target-feature -sha -target-feature -fma4 -target-feature -vpclmulqdq
 -target-feature -prfchw -target-feature +bmi2 -target-feature -xsavec -target-feature +fsgsbase -target-feature +popcnt -target-feature +aes -target-feature -avx512bitalg -t
arget-feature -xsaves -target-feature -avx512er -target-feature -avx512vnni -target-feature -avx512vpopcntdq -target-feature -clwb -target-feature -avx512f -target-feature -c
lzero -target-feature -pku -target-feature +mmx -target-feature -lwp -target-feature -xop -target-feature -rdseed -target-feature -ibt -target-feature -sse4a -target-feature
-avx512bw -target-feature -clflushopt -target-feature +xsave -target-feature -avx512vbmi2 -target-feature -avx512vl -target-feature -avx512cd -target-feature +avx -target-fea
ture -vaes -target-feature -rtm -target-feature +fma -target-feature +bmi -target-feature +rdrnd -target-feature -mwaitx -target-feature +sse4.1 -target-feature +sse4.2 -targ
et-feature +avx2 -target-feature +sse -target-feature +lzcnt -target-feature +pclmul -target-feature -prefetchwt1 -target-feature +f16c -target-feature +ssse3 -target-feature
 -sgx -target-feature -shstk -target-feature +cmov -target-feature -avx512vbmi -target-feature +movbe -target-feature +xsaveopt -target-feature -avx512dq -target-feature -adx
 -target-feature -avx512pf -target-feature +sse3 -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -momit-leaf-frame-pointer -resource-dir /ef
s/tools/tapir-6/build/lib/clang/6.0.0 -I/usr/include/x86_64-linux-gnu/ -c-isystem /efs/tools/tapir-6/build/lib/clang/5.0.0/include/ -cxx-isystem /efs/tools/tapir-6/build/lib/
clang/5.0.0/include/ -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.1/../../../../include/c++/5.4.1 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.1/../../../../inc
lude/x86_64-linux-gnu/c++/5.4.1 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.1/../../../../include/x86_64-linux-gnu/c++/5.4.1 -internal-isystem /usr/lib/gcc/x86_64-lin
ux-gnu/5.4.1/../../../../include/c++/5.4.1/backward -internal-isystem /usr/local/include -internal-isystem /efs/tools/tapir-6/build/lib/clang/6.0.0/include -internal-externc-
isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -Wall -std=c++17 -fdeprecated-macro -fdebug-compilation-di
r /efs/home/wheatman/extended-csr -ferror-limit 19 -fmessage-length 174 -fcilkplus -fsanitize=cilk -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option
-vectorize-loops -vectorize-slp -o /tmp/test2-94c907.o -x c++ test2.cpp
1.      <eof> parser at end of file
2.      Per-module optimization passes
3.      Running pass 'CilkSanitizer' on module 'test2.cpp'.
clang-6.0: error: unable to execute command: Segmentation fault
clang-6.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 6.0.0 (https://github.com/wsmoses/Tapir-Clang.git 190c083a326a7bee7dcf773d3ddd3e2e9240b719) (https://github.com/wsmoses/Tapir-LLVM.git 065b7e7497c8d91495a19b31c
6f144919cb77221)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /efs/tools/tapir-6/build/bin
clang-6.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-6.0: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-6.0: note: diagnostic msg: /tmp/test2-9e5f8e.cpp
clang-6.0: note: diagnostic msg: /tmp/test2-9e5f8e.sh
clang-6.0: note: diagnostic msg:

[test2-9e5f8e.sh.txt](https://github.com/wsmoses/Tapir-LLVM/files/2815322/test2-9e5f8e.sh.txt)
[test2-9e5f8e.txt](https://github.com/wsmoses/Tapir-LLVM/files/2815324/test2-9e5f8e.txt)

********************
make: *** [.run.cilksan] Error 254

**Comment by wsmoses** [comment]
Note this is not an issue on master, but rather with WIP-taskinfo @neboat assigning to you.

**Comment by neboat** [comment]
I've patched the WIP-taskinfo branch to fix this issue.
