### ISSUE TITLE
Running the benchmark suite

### ISSUE THREAD

**Issue by sanchitgrover** [wmoses/Parallel-IR#88]
I downloaded the benchmarks via http://tinyurl.com/TapirLLVMTesting and tried to run the test.sh script. However, I get errors saying the argument '-ftapir' is unknown. This can be found in the clib.sh which the other test scripts are sourcing. Has this argument been deprecated?

**Comment by wsmoses** [comment]
Hi @sanchitgrover, yeah we have slightly different arguments now. If you want the Cilk backend with Tapir -fcilkplus should be sufficient. If you want to run the test suite to check tapir's effectiveness I can point you to a repository with a newer version of the suite.

**Comment by neboat** [comment]
You can find an updated and expanded version of the test suite here: https://github.com/neboat/cilkbench.
