### ISSUE TITLE
Different behavior between Cilk code on 1 worker and serial elision on `xla_8` branch?

### ISSUE THREAD

**Issue by jsukha** [wmoses/Parallel-IR#89]
I was experimenting with one of the recent branches of Tapir, and I ran across an interesting situation and possible bug.    When I run the program compiling with a normal `for` loop, I get the answer that I expect.   However, when compiling with `_Cilk_for` with `-O1 -g`, I get a different result, and the program crashes on an assert I added, even when run with `CILK_NWORKERS=1`.      
[NabbitDCBug.zip](https://github.com/wsmoses/Tapir-LLVM/files/3398663/NabbitDCBug.zip)
When I compile with CIlk Plus from GCC 5.4.0, both serial and Cilk versions work as I expect.

I am using the `xla_8` branch of the various repos, and `clang++ --version` returns the following for me:
```
clang version 8.0.1 (https://github.com/wsmoses/Tapir-Clang.git c0169413e4d82fb2bc4a3c401fe4527f1838baa1) (https://github.com/wsmoses/Tapir-LLVM.git a038195c28ef6c41f5ad8e0947f061e71771cb6a)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/jsukha/sandbox/Tapir-Meta/src/build/bin
```

I reduced the original problem down to the following test programs.    I've included a Makefile + C++ code.
[NabbitDCBug.zip](https://github.com/wsmoses/Tapir-LLVM/files/3398542/NabbitDCBug.zip)

This code was originally implementing a blocked divide-and-conquer wavefront algorithm on a 2d grid.  It has been a while since I looked at the details of this code, so I'm not 100% sure there isn't a bug or race somewhere in the program.   But this code has worked through multiple incarnations of Cilk, so it would be interesting if there is a bug that is now being exposed by using Tapir.

Any ideas on what might be happening, and/or what is a good way to debug this issue?

**Comment by neboat** [comment]
This is what I get from trying to follow the Cilk Plus/LLVM code...

Apparently we were was miscalculating the loop bounds when the condition is `<=` or `>=`.  I just pushed a change to Tapir-Clang that seems to fix the problem.  If you update your clone of that repository and rebuild (an incremental build should suffice) then you should be back in business.

**Comment by jsukha** [comment]
Cool, that update to Tapir-Clang seems to work for me.      All the Cilk tests from the Nabbit repo (https://github.com/jsukha/nabbit) now seem to run correctly after this fix.

**Comment by neboat** [comment]
That's great!  Thanks for letting me know.
